# SPDX-License-Identifier: Apache-2.0
# West YAML manifest for Zephyr as Xen Dom0

manifest:
  self:
    path: zephyr-dom0-xt

  remotes:
    - name: xentroops
      url-base: https://github.com/xen-troops/
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos/

  projects:
    - name: zephyr
      remote: xentroops
      revision: f12d445f792d562f23c107379267f07674ab5ebd
      west-commands: scripts/west-commands.yml
    - name: zephyr-xenlib
      remote: xentroops
      revision: v3.2.0
    - name: fatfs
      remote: zephyrproject-rtos
      revision: 427159bf95ea49b7680facffaa29ad506b42709b
    - name: zephyr-xrun
      remote: xentroops
      revision: 5b6ecf274bac79b0be740693766a88d3eedf3b44
