# SPDX-License-Identifier: Apache-2.0
# West YAML manifest for Zephyr as Xen Dom0

manifest:
  self:
    path: zephyr-dom0-xt

  remotes:
    - name: xentroops
      url-base: https://github.com/xen-troops/
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos/
    - name: firscity
      url-base: https://github.com/firscity/

  projects:
    - name: zephyr
      remote: firscity
      revision: zephyr-v4.2.0-xt_rc1
      west-commands: scripts/west-commands.yml
    - name: zephyr-xenlib
      remote: xentroops
      revision: main
    - name: fatfs
      remote: zephyrproject-rtos
      revision: 16245c7c41d2b79e74984f49b5202551786b8a9b
    - name: zephyr-xrun
      remote: xentroops
      revision: main
